# Generated by Django 5.0.4 on 2026-03-23 07:00

import django.db.models.deletion
import stories.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_size', models.IntegerField(default=24)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('text_style', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic'), ('shadow', 'Shadow'), ('neon', 'Neon')], default='normal', max_length=20)),
                ('bg_color', models.CharField(default='#000000', max_length=7)),
                ('bg_gradient', models.CharField(blank=True, default='', max_length=100)),
                ('filter_name', models.CharField(choices=[('none', 'None'), ('clarendon', 'Clarendon'), ('gingham', 'Gingham'), ('moon', 'Moon'), ('lark', 'Lark'), ('reyes', 'Reyes'), ('juno', 'Juno'), ('slumber', 'Slumber'), ('crema', 'Crema')], default='none', max_length=20)),
                ('stickers_json', models.TextField(blank=True, default='[]')),
                ('music_title', models.CharField(blank=True, default='', max_length=100)),
                ('music_artist', models.CharField(blank=True, default='', max_length=100)),
                ('poll_question', models.CharField(blank=True, default='', max_length=120)),
                ('poll_option_a', models.CharField(blank=True, default='', max_length=60)),
                ('poll_option_b', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=stories.models.story_expires_at)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=1)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'viewer')},
            },
        ),
    ]
